[package]
name = "cosmic-dbus-networkmanager"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
bitflags = "1.3.2"
derive_builder = "0.10.2"
serde = { version = "1.0.134", features = ["derive"] }
zbus = "2.0.1"

[features]
